Repository ehs-symphony/test-website, pull requests merged in 2021-06, with the labels that each got.

#7 Change website title
  index.html
Labels: feature

#8 Move some files around to organize the website
  index.html
  pages/elements.html
  pages/generic.html
Labels: format

#9 Create issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, feature, project-management

#10 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, feature, project-management

#12 About page initial top text and iconography
  index.html
Labels: feature
